// <auto-generated />
using Ecommerce.Services.ProductAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ecommerce.Services.ProductAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ecommerce.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageLocalPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Tops",
                            Description = "A timeless staple for any wardrobe, the classic white T-shirt is made from 100% soft cotton for maximum comfort. Perfect for casual wear or layering.<br/>Tailored fit with a crew neckline for a sleek look.",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "Classic White T-Shirt",
                            Price = 25.0
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Bottoms",
                            Description = "Our denim jeans feature a classic straight-leg cut with a hint of stretch for comfort. The deep indigo wash offers versatility for both casual and semi-formal looks.<br/>Five-pocket styling with a button closure and zip fly.",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "Denim Jeans",
                            Price = 50.0
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Outerwear",
                            Description = "Crafted from premium genuine leather, this jacket is a symbol of timeless style. Features a zip front, stand-up collar, and quilted lining for warmth.<br/>Perfect for adding an edge to any outfit.",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "Leather Jacket",
                            Price = 120.0
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "Knitwear",
                            Description = "Luxuriously soft, this 100% cashmere sweater offers unparalleled comfort and warmth. The subtle ribbing at the cuffs, hem, and crew neck adds a touch of elegance.<br/>Ideal for layering during colder months.",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "Cashmere Sweater",
                            Price = 80.0
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryName = "Accessories",
                            Description = "Add a pop of color to your ensemble with our pure silk scarf. The lightweight, smooth fabric drapes beautifully and can be styled in various ways.<br/>Featuring an exclusive print for a unique touch.",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "Silk Scarf",
                            Price = 35.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
